version: "3.7"

services:

  db:
    image: postgres
    volumes:
      - data:/data-platform-ui/app/app
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: data-platform-ui.db

  webserver:
    image: data-platform-ui
    depends_on:
      - db
    env_file:
      - local_platform_env_vars.env
    command: bash -c "python ./app/manage.py runserver 0.0.0.0:8000"
    container_name: data-platform-ui.webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000

volumes:
  data: