version: '3.4'

services:
  app:
    image: ${IMAGE_NAME}
    ports:
      - 80:80
    logging:
      driver: syslog
      options:
        tag: "arids"
    env_file: /etc/dockerapp_env
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost/health"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 20s
